Parsing OpenStack Tempest test results from HTML pages
For passing test results:

    Downloaded content to: testr_results.html
    No failed tests found

For failing test results:

    Found 2 failed tests:
    ===========================================================================================================
    TEST: whitebox_neutron_tempest_plugin.tests.scenario.test_api_server.NeutronAPIServerTest.test_neutron_api_restart
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/neutron_tempest_plugin/common/utils.py", line 85, in wait_until_true
        eventlet.sleep(sleep)
      File "/usr/lib/python3.9/site-packages/eventlet/greenthread.py", line 36, in sleep
        hub.switch()
      File "/usr/lib/python3.9/site-packages/eventlet/hubs/hub.py", line 313, in switch
        return self.greenlet.switch()
    eventlet.timeout.Timeout: 120 seconds

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/test_api_server.py", line 49, in test_neutron_api_restart
        self.set_service_setting(file=wb_utils.get_ml2_conf_file(),
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/base.py", line 499, in set_service_setting
        common_utils.wait_until_true(
      File "/usr/lib/python3.9/site-packages/neutron_tempest_plugin/common/utils.py", line 89, in wait_until_true
        raise exception
    RuntimeError: 'neutron-65995b5d7c-8hd9l' pod not replaced in 120 seconds:
    ['neutron-65995b5d7c-8hd9l', 'neutron-65995b5d7c-9jm2l', 'neutron-65995b5d7c-d898v']
    ===========================================================================================================
    TEST: whitebox_neutron_tempest_plugin.tests.scenario.test_mtu.GatewayMtuTestUdp.test_south_to_north_pmtud_udp_basic[id-7f7470ff-31b4-4ad8-bfa7-82dcca174744]
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/test_mtu.py", line 247, in test_south_to_north_pmtud_udp_basic
        self.check_pmtud_basic()
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/test_mtu.py", line 202, in check_pmtud_basic
        self.validate_next_hop_mtu(
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/test_mtu.py", line 190, in validate_next_hop_mtu
        self._verify_capture_for_icmp_unreacheable(
      File "/usr/lib/python3.9/site-packages/whitebox_neutron_tempest_plugin/tests/scenario/test_mtu.py", line 114, in _verify_capture_for_icmp_unreacheable
        self.assertEqual(
      File "/usr/lib/python3.9/site-packages/testtools/testcase.py", line 393, in assertEqual
        self.assertThat(observed, matcher, message)
      File "/usr/lib/python3.9/site-packages/testtools/testcase.py", line 480, in assertThat
        raise mismatch_error
    testtools.matchers._impl.MismatchError: 0 != 1442: Delivered data has size 0 bytes while expected 1442.